#ifndef DD_AI_H
#define DD_AI_H

#define SMARTCTL_SYSTEM_PROMPT \
    "Act as an expert in storage device health diagnostics (HDD, SATA SSD, NVMe).\n" \
    "Analyze the JSON output generated by `smartctl` that I will provide below.\n\n" \
    "Reply with AT MOST 5 LINES, no more, covering only:\n" \
    "1. Drive model and capacity.\n" \
    "2. Overall health: Excellent / Caution / Critical.\n" \
    "3. The single most relevant wear or reliability metric (e.g. percentage_used, " \
    "reallocated sectors, media errors, temperature).\n" \
    "4. One concrete recommended action, only if something needs attention.\n\n" \
    "Plain text only: no headings, no tables, no markdown, no preamble. Be direct and to the point.\n"

#define SMARTCTL_FULL_PROMPT_FMT \
    SMARTCTL_SYSTEM_PROMPT \
    "\n--- SMARTCTL JSON OUTPUT ---\n" \
    "%s\n"

#define OPENAI_URL "https://api.openai.com/v1/chat/completions"
#define ANTHROPIC_URL "https://api.anthropic.com/v1/messages"
#define GEMINI_URL "https://generativelanguage.googleapis.com/v1beta/models/%s:generateContent?key=%s"

typedef enum {
    PROVIDER_NONE = -1,
    PROVIDER_OPENAI,
    PROVIDER_ANTHROPIC,
    PROVIDER_GEMINI
} ai_provider;

typedef struct {
    char openai_key[256];
    char anthropic_key[256];
    char gemini_key[256];
} key_store;

typedef struct {
    ai_provider provider;
    const char *model;
    const char *prompt;
} ai_request;

#define OPENAI_DEFAULT_MODEL "gpt-4o-mini"
#define ANTHROPIC_DEFAULT_MODEL "claude-sonnet-5"
#define GEMINI_DEFAULT_MODEL "gemini-1.5-flash"

ai_provider load_keys(key_store *ks);

const char *default_model_for_provider(ai_provider provider);

void send_ai_prompt(const key_store *ks, const ai_request *req);

#endif
